<?php

/**
 * BaseUserStatistic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $num_bets
 * @property integer $num_accesses
 * @property integer $num_wins
 * @property integer $user_id
 * @property sfGuardUser $User
 * 
 * @method integer       getNumBets()      Returns the current record's "num_bets" value
 * @method integer       getNumAccesses()  Returns the current record's "num_accesses" value
 * @method integer       getNumWins()      Returns the current record's "num_wins" value
 * @method integer       getUserId()       Returns the current record's "user_id" value
 * @method sfGuardUser   getUser()         Returns the current record's "User" value
 * @method UserStatistic setNumBets()      Sets the current record's "num_bets" value
 * @method UserStatistic setNumAccesses()  Sets the current record's "num_accesses" value
 * @method UserStatistic setNumWins()      Sets the current record's "num_wins" value
 * @method UserStatistic setUserId()       Sets the current record's "user_id" value
 * @method UserStatistic setUser()         Sets the current record's "User" value
 * 
 * @package    game_notifier
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserStatistic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_statistic');
        $this->hasColumn('num_bets', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('num_accesses', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('num_wins', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}