<?php

/**
 * BaseSuperenalottoWinUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $superenalotto_win_id
 * @property SuperenalottoWin $SuperenalottoWin
 * @property sfGuardUser $User
 * 
 * @method integer              getUserId()               Returns the current record's "user_id" value
 * @method integer              getSuperenalottoWinId()   Returns the current record's "superenalotto_win_id" value
 * @method SuperenalottoWin     getSuperenalottoWin()     Returns the current record's "SuperenalottoWin" value
 * @method sfGuardUser          getUser()                 Returns the current record's "User" value
 * @method SuperenalottoWinUser setUserId()               Sets the current record's "user_id" value
 * @method SuperenalottoWinUser setSuperenalottoWinId()   Sets the current record's "superenalotto_win_id" value
 * @method SuperenalottoWinUser setSuperenalottoWin()     Sets the current record's "SuperenalottoWin" value
 * @method SuperenalottoWinUser setUser()                 Sets the current record's "User" value
 * 
 * @package    game_notifier
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSuperenalottoWinUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('superenalotto_win_user');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('superenalotto_win_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SuperenalottoWin', array(
             'local' => 'superenalotto_win_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}