<?php

/**
 * BaseBannerConfiguration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $page_routing
 * @property clob $banner_text
 * @property boolean $is_default
 * @property enum $position
 * 
 * @method string              getPageRouting()  Returns the current record's "page_routing" value
 * @method clob                getBannerText()   Returns the current record's "banner_text" value
 * @method boolean             getIsDefault()    Returns the current record's "is_default" value
 * @method enum                getPosition()     Returns the current record's "position" value
 * @method BannerConfiguration setPageRouting()  Sets the current record's "page_routing" value
 * @method BannerConfiguration setBannerText()   Sets the current record's "banner_text" value
 * @method BannerConfiguration setIsDefault()    Sets the current record's "is_default" value
 * @method BannerConfiguration setPosition()     Sets the current record's "position" value
 * 
 * @package    game_notifier
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBannerConfiguration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banner_configuration');
        $this->hasColumn('page_routing', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('banner_text', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('is_default', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('position', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'top',
              1 => 'bottom',
              2 => 'left',
              3 => 'right',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}