<?php

/**
 * BaseSuperenalottoWin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $numbers_extracted
 * @property string $contest_id
 * @property integer $superstar
 * @property integer $game_id
 * @property Game $Game
 * @property Doctrine_Collection $WinningUsers
 * @property Doctrine_Collection $Wins
 * 
 * @method string              getNumbersExtracted()  Returns the current record's "numbers_extracted" value
 * @method string              getContestId()         Returns the current record's "contest_id" value
 * @method integer             getSuperstar()         Returns the current record's "superstar" value
 * @method integer             getGameId()            Returns the current record's "game_id" value
 * @method Game                getGame()              Returns the current record's "Game" value
 * @method Doctrine_Collection getWinningUsers()      Returns the current record's "WinningUsers" collection
 * @method Doctrine_Collection getWins()              Returns the current record's "Wins" collection
 * @method SuperenalottoWin    setNumbersExtracted()  Sets the current record's "numbers_extracted" value
 * @method SuperenalottoWin    setContestId()         Sets the current record's "contest_id" value
 * @method SuperenalottoWin    setSuperstar()         Sets the current record's "superstar" value
 * @method SuperenalottoWin    setGameId()            Sets the current record's "game_id" value
 * @method SuperenalottoWin    setGame()              Sets the current record's "Game" value
 * @method SuperenalottoWin    setWinningUsers()      Sets the current record's "WinningUsers" collection
 * @method SuperenalottoWin    setWins()              Sets the current record's "Wins" collection
 * 
 * @package    game_notifier
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSuperenalottoWin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('superenalotto_win');
        $this->hasColumn('numbers_extracted', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('contest_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('superstar', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('game_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Game', array(
             'local' => 'game_id',
             'foreign' => 'id'));

        $this->hasMany('sfGuardUser as WinningUsers', array(
             'refClass' => 'SuperenalottoWinUser',
             'local' => 'superenalotto_win_id',
             'foreign' => 'user_id'));

        $this->hasMany('SuperenalottoWinUser as Wins', array(
             'local' => 'id',
             'foreign' => 'superenalotto_win_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}