<?php

/**
 * BaseGame
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $game_configuration_id
 * @property string $title
 * @property string $scheduled_time
 * @property GameConfiguration $GameConfiguration
 * @property Doctrine_Collection $SuperenalottoBets
 * @property Doctrine_Collection $SuperenalottoWins
 * 
 * @method integer             getGameConfigurationId()   Returns the current record's "game_configuration_id" value
 * @method string              getTitle()                 Returns the current record's "title" value
 * @method string              getScheduledTime()         Returns the current record's "scheduled_time" value
 * @method GameConfiguration   getGameConfiguration()     Returns the current record's "GameConfiguration" value
 * @method Doctrine_Collection getSuperenalottoBets()     Returns the current record's "SuperenalottoBets" collection
 * @method Doctrine_Collection getSuperenalottoWins()     Returns the current record's "SuperenalottoWins" collection
 * @method Game                setGameConfigurationId()   Sets the current record's "game_configuration_id" value
 * @method Game                setTitle()                 Sets the current record's "title" value
 * @method Game                setScheduledTime()         Sets the current record's "scheduled_time" value
 * @method Game                setGameConfiguration()     Sets the current record's "GameConfiguration" value
 * @method Game                setSuperenalottoBets()     Sets the current record's "SuperenalottoBets" collection
 * @method Game                setSuperenalottoWins()     Sets the current record's "SuperenalottoWins" collection
 * 
 * @package    game_notifier
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGame extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('game');
        $this->hasColumn('game_configuration_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('scheduled_time', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GameConfiguration', array(
             'local' => 'game_configuration_id',
             'foreign' => 'id'));

        $this->hasMany('SuperenalottoBet as SuperenalottoBets', array(
             'local' => 'id',
             'foreign' => 'game_id'));

        $this->hasMany('SuperenalottoWin as SuperenalottoWins', array(
             'local' => 'id',
             'foreign' => 'game_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}