superenalotto_bet:
  class: sfDoctrineRouteCollection
  options:
    model:                SuperenalottoBet
    module:               superenalotto_bet
    prefix_path:          /superenalotto_bet
    column:               id
    with_wildcard_routes: true

user_statistic:
  class: sfDoctrineRouteCollection
  options:
    model:                UserStatistic
    module:               user_statistic
    prefix_path:          /user_statistic
    column:               id
    with_wildcard_routes: true

superenalotto_win:
  class: sfDoctrineRouteCollection
  options:
    model:                SuperenalottoWin
    module:               superenalotto_win
    prefix_path:          /superenalotto_win
    column:               id
    with_wildcard_routes: true

game_configuration:
  class: sfDoctrineRouteCollection
  options:
    model:                GameConfiguration
    module:               game_configuration
    prefix_path:          /game_configuration
    column:               id
    with_wildcard_routes: true

game:
  class: sfDoctrineRouteCollection
  options:
    model:                Game
    module:               game
    prefix_path:          /game
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing


testScraper:
  url: /testScraper
  param:
    module: testScraper
    action: index

# default rules
homepage:
  url: /
  param:
    module: sfAdminDash
    action: dashboard
sf_guard_signin:
  url: /login
  param:
    module: sfGuardAuth
    action: signin
sf_guard_signout:
  url: /logout
  param:
    module: sfGuardAuth
    action: signout
sf_guard_password:
  url: /request_password
  param:
    module: sfGuardAuth
    action: password
    
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
