<?php

/**
 * ActionLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActionLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActionLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActionLog');
    }
}