<?php

/**
 * BannerConfigurationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BannerConfigurationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BannerConfigurationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BannerConfiguration');
    }
}