<?php

/**
 * GameConfigurationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameConfigurationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameConfigurationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GameConfiguration');
    }
}