<?php

/**
 * SuperenalottoWinTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SuperenalottoWinTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SuperenalottoWinTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SuperenalottoWin');
    }
}