<?php

/**
 * UserStatisticTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserStatisticTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserStatisticTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserStatistic');
    }
}