### SUPERENALOTTO CARD ROUTES ###
superenalotto_card:
  url:   /superenalotto_card
  param: { module: superenalotto_card, action: showSuperenalottoCard }
check_save_card:
  url:   /check_save_card
  param: { module: superenalotto_card, action: checkSaveCard }
