### SUPERENALOTTO CARD ROUTES ###
superenalotto_card:
  url:   superenalottoCard/gameId/:gameId/contestId/:contestId
  param: { module: superenalotto_card, action: showSuperenalottoCard }
  requirements:
    gameId: \d+
    contestId: \d+
check_save_card:
  url:   /check_save_card
  param: { module: superenalotto_card, action: checkSaveCard }

  
homepage:
  url:   /
  param: { module: main, action: index }
  