<?php

/**
 * Pluginnet7EmailTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Pluginnet7EmailTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Pluginnet7EmailTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pluginnet7EmailTemplate');
    }
    
	public static function retrieveByNameAndLang($name, $lang){
		$q = Doctrine_Query::create()
		->from('net7EmailTemplate e')
		->where('e.name = ?' , $name)
		->leftJoin('e.Translation et')
		->andWhere('et.lang = ?', $lang);

		return $q->fetchOne();
	}
}