#############################
############ User info ######
#############################
SfGuardUserProfile:
  columns:
    user_id:          { type: integer, notnull: true }
    first_name:       { type: string(30) }
    last_name:        { type: string(30) }
    facebook_uid:     { type: string(20) }
    # VERIFICARE SE è necessario lasciarlo
    email:            { type: string(255) }
  indexes:
    facebook_uid_index:
      fields: [facebook_uid]
      unique: true
    email_index:
      fields: [email]
      unique: true
  relations:
    sfGuardUser:
      type: one
      foreignType: one
      class: sfGuardUser
      local: user_id
      foreign: id
      onDelete: cascade
      foreignAlias: Profile  


GameConfiguration:
  actAs:
    Timestampable: ~
    
  columns:
    title: string(255)
    class_to_use: string(255)
    configurations_steps: clob
    
Game:
  actAs:
    Timestampable: ~
  columns:
    game_configuration_id: integer
    title: string(255)
    scheduled_time: string(255)
  relations:
    GameConfiguration:
      local: game_configuration_id
      foreign: id
      foreignAlias: Games
      class:  GameConfiguration
      
      
      
  ###########################
  ### SUPERENALOTTO ###
  ###########################
      
SuperenalottoBet:
  actAs:
    Timestampable: ~
    Signable:      ~ 
  columns: 
    numbers_played: string(255)
    superstar: integer
    contest_id: string(255) # identificativo del concorso
    game_id: integer
    user_id: integer
  relations:
    Game:
      class: Game
      foreign: id
      local: game_id
      foreignAlias: SuperenalottoBets
    User:
      class: sfGuardUser
      local: user_id
      foreign: id
      foreignAlias: SuperenalottoBets 
      
      
SuperenalottoWin:
  actAs:
    Timestampable: ~
  columns:
    numbers_extracted: string(255)
    contest_id: string(255) # identificativo del concorso
    superstar: integer
    game_id: integer
  relations:
    Game:
      class: Game
      foreign: id
      local: game_id
      foreignAlias: SuperenalottoWins
    WinningUsers:
      local: superenalotto_win_id
      class: sfGuardUser
      foreign: user_id 
      refClass: SuperenalottoWinUser
      foreignAlias: SuperenalottoWins

SuperenalottoWinUser:
  actAs:
    Timestampable: ~
  columns:
    user_id: integer
    superenalotto_win_id: integer
    
  relations:
    SuperenalottoWin:
      class: SuperenalottoWin
      foreign: id
      local: superenalotto_win_id
      foreignAlias: Wins
      onDelete: cascade
    User:
      class: sfGuardUser
      local: user_id
      foreign: id
      foreignAlias: Wins 
      # qui nessun ondelete...teniamo i dati anche se l'utente viene eliminato
  
  
#############################
######  LOGS  ###############
#############################

ActionLog:
  actAs:
    Timestampable: ~
  columns:
    user_id:  integer
    username: string(255) 
    action:  string(60)
    ip:      string(60)
    browser: string(255)
    session_id: string(255)
    app_type: string(60)
    name: string(255)
    surname: string(255)


################################
###### STATISTICS ##############
###############################


UserStatistic:
  columns:
    num_bets: integer
    num_accesses: integer
    num_wins: integer
    user_id: integer
  relations: 
    User:
      class: sfGuardUser
      local: user_id
      foreign: id
      foreignAlias: UserStatistics 

#####################################
##### banner configuration###########
#####################################      
                  
BannerConfiguration:
  columns:
    page_routing: string(255)
    banner_text: clob
    is_default: boolean
    
    position:
      type: enum
      values: [top, bottom, left, right]
    
                            