<?php

/**
 * net7EmailTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class net7EmailTemplateTable extends Pluginnet7EmailTemplateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object net7EmailTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('net7EmailTemplate');
    }
}